name: Transpile Butane to Ignition

on:
  push:
    branches:
      - main # Or your default branch name
    paths:
      - 'butane/**.bu'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write # Required for the default token, good practice to keep

jobs:
  transpile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Transpile Butane files
        run: |
          # Ensure the output directory exists
          mkdir -p ignition

          # Loop through all .bu files in the butane directory
          for bu_file in butane/*.bu; do
            # Get the base filename without the .bu extension
            filename=$(basename "$bu_file" .bu)
            ign_file="ignition/${filename}.ign"
            
            echo "Transpiling ${bu_file} to ${ign_file}"
            
            # Use the official Butane container to transpile the file.
            # We mount the current directory into the container and set it as the working directory.
            # --files-dir tells butane where to look for other files if your config references any.
            podman run --rm -v .:/app -w /app quay.io/coreos/butane:release \
              --files-dir butane \
              --output "${ign_file}" \
              "${bu_file}"
          done

      - name: Create Pull Request with Ignition changes
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }} # Use PAT to trigger subsequent workflows
          commit-message: "chore: Transpile Butane configs to Ignition"
          title: "chore: Update Ignition files from Butane"
          body: "Automated update of Ignition files after changes to Butane source files."
          branch: "chore/bot/update-ignition-files"
          delete-branch: true

      - name: Approve the PR
        if: steps.cpr.outputs.pull-request-number != ''
        run: gh pr review --approve "${{ steps.cpr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}

      - name: Enable auto-merge for the PR
        if: steps.cpr.outputs.pull-request-number != ''
        run: gh pr merge --auto --squash "${{ steps.cpr.outputs.pull-request-url }}"
        env:
          GH_TOKEN: ${{ secrets.BOT_ACCESS_TOKEN }}
