name: Validate Butane

on:
  pull_request:
    paths:
      - 'butane/**.bu'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Butane files
        run: |
          # Loop through all .bu files in the butane directory
          for bu_file in butane/*.bu; do
            echo "Validating ${bu_file}"
            
            # Use the official Butane container to validate the file by transpiling to /dev/null.
            # This uses the same container and arguments as the transpile workflow.
            podman run --rm -v .:/app -w /app quay.io/coreos/butane:release \
              --files-dir butane \
              --strict \
              --output /dev/null \
              "${bu_file}"
          done
